### ISSUE TITLE
[CSS] Style broken on customize theme

### ISSUE THREAD

**Issue by dhduc** [unetstudio/magento-2-social-share#25]

**Comment by AakashCodeLab** [comment]
is this still open?

**Comment by dhduc** [comment]
@aakash18012 yep, it happens on customizing theme that using ```box-sizing: border-box``` on page css style. I'm going to fix it.

**Comment by dhduc** [comment]
#26

**Comment by dhduc** [comment]
Fixed on 1.0.9
